-- =============================================================
-- ラボカレ  optional/99_drop_culture_links.sql
-- 未使用テーブル public.culture_links を削除します（任意・元に戻せません）。
--
-- culture_links は「継代培養を管理」ページの初期版（05_culture_links.sql）で
-- 作ったテーブルです。その後 08_culture_media.sql の culture_media に
-- 置き換わり、アプリのコードからは一切参照されていません
-- （`grep -r culture_links` の結果は0件）。
--
-- 00_baseline.sql はこのテーブルを作りません。新しいプロジェクトには
-- 最初から存在しないので、このファイルを実行する必要があるのは
-- 2025年に 05 を流した既存プロジェクトだけです。
--
-- 実行しなくても害はありません（空のテーブルが1つ残るだけです）。
-- 中身を確認してから消したい場合は、先にこちらを実行してください:
--   select count(*) from public.culture_links;
--
-- optional/ に置いてあるのは、00_baseline.sql の中に
-- 「コメントを外すと消える drop 文」を置きたくないためです。
-- =============================================================

drop table if exists public.culture_links;
